name: smart_qr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scan: ^1.6.0
  images_picker: ^1.2.10
  gallery_saver: ^2.3.2
  path_provider: ^2.0.9
  qr_flutter: ^4.0.0
  # barcode_parser: ^0.2.0
  barcode_parser:
    path: packages/barcode_parser
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_riverpod: ^1.0.4
  uuid: ^3.0.6
  url_launcher: ^6.1.2
  share_plus: ^4.0.3
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  icons_launcher: ^1.1.7
  flutter_native_splash: ^2.1.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  image_path: 'assets/images/launcher_icon.png'
  ios: false
  android: true
flutter_native_splash:
  color: "#42a5f5"
  image: 'assets/images/launcher_icon.png'
  ios: false
  web: false
